#!/bin/sh
if [ "$1" == "" ]
then
   javac -target 1.6 -source 1.6 -Xlint:-options -Xlint:deprecation -Xlint:unchecked -cp .:darwin.jar *.java
else
   javac -target 1.6 -source 1.6 -Xlint:-options -Xlint:deprecation -Xlint:unchecked -cp .:darwin.jar $@
fi

